name: test

on:
  push:

jobs:
  unit-test:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '8'

      - name: Install boot on MS-Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          $env:BOOT_BIN_DIR="$HOME\.boot\bin"

          if (!(Test-Path $env:BOOT_BIN_DIR)) {new-item "$env:BOOT_BIN_DIR" -ItemType directory}
          iwr -Uri https://github.com/boot-clj/boot-bin/releases/download/latest/boot.exe `
          -outfile $env:BOOT_BIN_DIR/boot.exe
          echo $env:BOOT_BIN_DIR | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          # reg add "HKLM\SOFTWARE\JavaSoft\Java Development Kit\1.8" /v JAVAHome /d "$env:JAVA_HOME" /f
          & "$env:BOOT_BIN_DIR/boot.exe" -V

